// ============================================================
// 판교 퀘스트 — 빌런(적) 정의
// 출근길/회사생활을 은유한 유쾌한 빌런들.
// 스테이지 스케일은 stages.ts 의 배율로 곱해진다.
// ============================================================

import type { EnemyDef, EnemyKind } from "./types";

export const ENEMY_DEFS: Record<EnemyKind, EnemyDef> = {
  gate: {
    kind: "gate",
    name: "잔액부족 게이트",
    hp: 40,
    atk: 8,
    speed: 0.9,
    radius: 18,
    exp: 8,
    color: "#e8544f",
    accent: "#ffd35a",
    knockbackResist: 0.2,
    desc: "삑— 잔액이 부족합니다. 느리지만 끈질기게 길을 막는다.",
  },
  crowd: {
    kind: "crowd",
    name: "밀치는 인파",
    hp: 26,
    atk: 7,
    speed: 1.75,
    radius: 14,
    exp: 6,
    color: "#7c86ff",
    accent: "#c9ceff",
    knockbackResist: 0,
    desc: "수십 명이 동시에 밀려온다. 개별론 약하지만 떼로 몰려온다.",
  },
  lost: {
    kind: "lost",
    name: "길잃은 환승객",
    hp: 46,
    atk: 10,
    speed: 1.3,
    radius: 16,
    exp: 11,
    color: "#3fbf8f",
    accent: "#d5fff0",
    knockbackResist: 0.1,
    desc: "여긴 어디… 배회하다가 갑자기 당신에게 돌진한다.",
  },
  escalator: {
    kind: "escalator",
    name: "역주행 에스컬레이터",
    hp: 70,
    atk: 12,
    speed: 2.1,
    radius: 20,
    exp: 15,
    color: "#b0b6c4",
    accent: "#ffd35a",
    knockbackResist: 1, // 넉백 무효
    desc: "정해진 라인을 왕복하며 밀어붙인다. 밀어낼 수 없다. 피해라.",
  },
  kickboard: {
    kind: "kickboard",
    name: "무단질주 킥보드",
    hp: 40,
    atk: 14,
    speed: 6.4,
    radius: 15,
    exp: 14,
    color: "#ff8a3d",
    accent: "#fff0c8",
    knockbackResist: 0.5,
    desc: "예고 후 직선으로 폭주. 대시 직전 잠깐 멈칫할 때 노려라.",
  },
  signal: {
    kind: "signal",
    name: "변덕쟁이 신호등",
    hp: 90,
    atk: 11,
    speed: 1.1,
    radius: 19,
    exp: 20,
    color: "#e8544f",
    accent: "#3fbf8f",
    knockbackResist: 0.6,
    desc: "빨간불엔 무적, 투사체 발사. 초록불로 바뀔 때만 때릴 수 있다.",
  },
  notification: {
    kind: "notification",
    name: "푸시 알림 떼",
    hp: 22,
    atk: 9,
    speed: 1.6,
    radius: 13,
    exp: 9,
    color: "#ff5d8f",
    accent: "#ffffff",
    knockbackResist: 0,
    desc: "딩— 딩— 사방에서 날아와 투사체를 쏜다. 약하지만 성가시다.",
  },
  queue: {
    kind: "queue",
    name: "끝없는 커피 대기줄",
    hp: 170,
    atk: 16,
    speed: 0.7,
    radius: 26,
    exp: 30,
    color: "#8a5a2b",
    accent: "#e8c9a0",
    knockbackResist: 0.85,
    desc: "느리지만 거대한 탱커. 아메리카노 한 잔이 이렇게 멀다.",
  },
  badge: {
    kind: "badge",
    name: "출입증 인식오류",
    hp: 120,
    atk: 10,
    speed: 0,
    radius: 22,
    exp: 26,
    color: "#2a5cff",
    accent: "#ff5d5d",
    knockbackResist: 1,
    desc: "고정 포탑. 인식 실패— 사방으로 링 모양 투사체를 뿌린다.",
  },
  boss: {
    kind: "boss",
    name: "먼데이 모닝",
    hp: 1500,
    atk: 20,
    speed: 1.3,
    radius: 46,
    exp: 0,
    color: "#1a1030",
    accent: "#ff3a3a",
    knockbackResist: 1,
    desc: "월요일 아침의 화신. 데드라인·긴급회의·알림폭탄, 3단 페이즈로 짓누른다.",
  },
};

// 도감 표시용 순서
export const ENEMY_ORDER: EnemyKind[] = [
  "gate",
  "crowd",
  "lost",
  "escalator",
  "kickboard",
  "signal",
  "notification",
  "queue",
  "badge",
  "boss",
];
